### ISSUE TITLE
Mass Leaderboard

### ISSUE THREAD

**Issue by relasine** [dmeskis/pitch_battles_be#35]

**Comment by dmeskis** [comment]
Create an endpoint for a leaderboard.

api/v1/leaderboards?type=level_one
api/v1/leaderboards?type=level_two
api/v1/leaderboards?type=level_three
api/v1/leaderboards?type=level_four
api/v1/leaderboards?type=all_levels

Leaderboards controller accepts a type and then returns the top 100 scores accordingly.

We need top 100 fastest times for each level, as well as the fastest total time.

We want to return user id, first and last name, the score, and the date which they achieved that score.
